name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET }}
          aws-region: us-east-1

      - name: Get runner ip address
        id: ip
        uses: haythem/public-ip@v1.2

#       - name: Whitelist runner ip address
#         run: |
#           aws ec2 authorize-security-group-ingress \
#             --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
#             --protocol tcp \
#             --port 22 \
#             --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "~/app/expenses"

      - name: Run migrations
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/app/expenses
            npm install
            ./node_modules/.bin/typeorm migration:run
            pm2 restart expenses_api
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}

      - name: Revoke runner ip address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
